### ISSUE TITLE
Styling Issue on Firefox and Edge

### ISSUE THREAD

**Issue by hahnmichaelf** [MrLuit/EtherScamDB#769]
At https://etherscamdb.info/report a styling error occurs where there is overlapping texts. This does not occur in Chrome or IE.

![image](https://user-images.githubusercontent.com/29407814/39407745-f975282c-4b98-11e8-81a5-7ec8c6cb364e.png)

**Comment by MrLuit** [comment]
I did some research and this turned out to be Firefox and Edge handling percentages on flex containers differently from the way Chrome, Safari, and Opera are doing it. The W3C CSSWG, Microsoft, and Mozilla have recently adopted Google's behavior and such this should be fixed as of [Firefox 60](https://www.mozilla.org/en-US/firefox/60.0/releasenotes/) (fully released as of May 9) and [Edge 42.17134](https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/17134/?compareWith=16299) (released as of April 30).

Quoting [`@atanassov`](https://github.com/w3c/csswg-drafts/issues/2085#issuecomment-360244244) (Edge; 24 Jan 2018):

> As I stated during the WG discussion, our intention in Edge is to implement the blink and webkit behavior, i.e. resolve padding/margin-top/bottom values against the available inline size (width). Our decision is driven solely due to the compatibility issues experienced by our users.

Quoting [`@dholbert`](https://github.com/w3c/csswg-drafts/issues/2085#issuecomment-360602313) (Firefox; 25 Jan 2018):

> We're going to change as well (away from the symmetric behavior, to the inline-axis behavior).

### Sources
- ["How should we resolve percentage margins and padding on grid and flex items?"](https://rachelandrew.co.uk/archives/2017/12/20/how-should-we-resolve-percentage-margins-and-padding-on-grid-and-flex-items/)
- [CSS WG thread](https://github.com/w3c/csswg-drafts/issues/2085#issuecomment-362000362)
- [Mozilla discussion](https://bugzilla.mozilla.org/show_bug.cgi?id=958714#c50)
- [Edge discussion](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14517293/)
- [Full W3C mailing list](https://lists.w3.org/Archives/Public/www-style/2015Sep/0038.html)
- [Heights for flexbox children intrinsically-sized with CSS are not computed properly in Firefox](https://github.com/philipwalton/flexbugs/issues/87)

---------------------
I'm closing this issue for now, if someone wants to add something to the discussion feel free to reopen it
